# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/connect/integration/BlockingConnectorTest.java": {
        "shard_count": 2,
        "size": "large",
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConfluentLicenseInjectionIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConfluentV1MetadataResourceTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConnectWorkerIntegrationTest.java": {
        "shard_count": 3,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConnectorClientPolicyIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConnectorRestartApiIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConnectorTopicsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConnectorTracingIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ConnectorValidationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ErrorHandlingIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ExactlyOnceSourceIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/ExampleConnectIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/InternalTopicsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/LogEventsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/OffsetsApiIntegrationTest.java": {
        "shard_count": 7,
        "size": "large",
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/RebalanceSourceConnectorsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/RestExtensionIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/RestForwardingIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/SessionedProtocolIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/SinkConnectorsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/SourceConnectorsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/StandaloneWorkerIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/StartAndStopCounterTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/StartAndStopLatchTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/integration/TransformationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    }
}
