# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/server/log/remote/metadata/storage/RemoteLogSegmentLifecycleTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/server/log/remote/metadata/storage/TopicBasedRemoteLogMetadataManagerMultipleSubscriptionsTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/server/log/remote/metadata/storage/TopicBasedRemoteLogMetadataManagerRestartTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/server/log/remote/storage/RemoteLogMetadataManagerTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tiered/storage/TieredStorageTestHarness.java": {
        "tags": [
            "integration"
        ]
    }
}
