# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/tools/DeleteRecordsCommandTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/FeatureCommandTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/GetOffsetShellTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/LeaderElectionCommandTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/MetadataQuorumCommandTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/TopicCommandIntegrationTest.java": {
        "shard_count": 4,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/consumer/group/DeleteOffsetsConsumerGroupCommandIntegrationTest.java": {
        "size": "large",
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/consumer/group/DescribeConsumerGroupTest.java": {
        "shard_count": 5,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/consumer/group/ListConsumerGroupTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/tools/consumer/group/ResetConsumerGroupOffsetTest.java": {
        "shard_count": 3,
        "size": "large",
        "tags": [
            "cpu:2"
        ]
    }
}
