# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/connect/mirror/integration/DedicatedMirrorIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/mirror/integration/IdentityReplicationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/mirror/integration/MirrorConnectorsIntegrationBaseTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/mirror/integration/MirrorConnectorsIntegrationExactlyOnceTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/mirror/integration/MirrorConnectorsIntegrationSSLTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/mirror/integration/MirrorConnectorsWithCustomForwardingAdminIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    }
}
