# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/streams/integration/AdjustStreamThreadCountTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/ConsistencyVectorIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/CustomHandlerIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/EOSUncleanShutdownIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/EmitOnChangeIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/EosIntegrationTest.java": {
        "shard_count": 8,
        "size": "large",
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/EosV2UpgradeIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/FineGrainedAutoResetIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/GlobalKTableEOSIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/GlobalKTableIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/GlobalStateReprocessTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/GlobalThreadShutDownOrderTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/HighAvailabilityTaskAssignorIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/IQv2IntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/IQv2StoreIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/IQv2VersionedStoreIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/InternalTopicIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/JoinGracePeriodDurabilityIntegrationTest.java": {
        "shard_count": 4,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/JoinStoreIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/JoinWithIncompleteMetadataIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KStreamAggregationDedupIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KStreamAggregationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KStreamKStreamIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KStreamRepartitionIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KStreamTransformIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableEfficientRangeQueryTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableKTableForeignKeyInnerJoinCustomPartitionerIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableKTableForeignKeyInnerJoinMultiIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableKTableForeignKeyJoinDistributedTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableKTableForeignKeyJoinIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableKTableForeignKeyJoinMaterializationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KTableSourceTopicRestartIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/KafkaStreamsCloseOptionsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/LagFetchIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/MetricsIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/MetricsReporterIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/NamedTopologyIntegrationTest.java": {
        "shard_count": 3,
        "size": "large",
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/OptimizedKTableIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/PauseResumeIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/PositionRestartIntegrationTest.java": {
        "shard_count": 4,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/PurgeRepartitionTopicIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/QueryableStateIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/RangeQueryIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/RegexSourceIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/ResetIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/ResetIntegrationWithSslTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/ResetPartitionTimeIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/RestoreIntegrationTest.java": {
        "shard_count": 3,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/RocksDBMetricsIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/SelfJoinUpgradeIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/SlidingWindowedKStreamIntegrationTest.java": {
        "shard_count": 3,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/SmokeTestDriverIntegrationTest.java": {
        "shard_count": 4,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StandbyTaskCreationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StandbyTaskEOSIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StandbyTaskEOSMultiRebalanceIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StateDirectoryIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StoreQueryIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StoreUpgradeIntegrationTest.java": {
        "shard_count": 4,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StreamStreamJoinIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StreamTableJoinIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StreamTableJoinTopologyOptimizationIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StreamTableJoinWithGraceIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StreamsUncaughtExceptionHandlerIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/StreamsUpgradeTestIntegrationTest.java": {
        "shard_count": 1,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/SuppressionDurabilityIntegrationTest.java": {
        "shard_count": 3,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/SuppressionIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/TableTableJoinIntegrationTest.java": {
        "shard_count": 4,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/TaskAssignorIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/TaskMetadataIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/TimeWindowedKStreamIntegrationTest.java": {
        "shard_count": 3,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/integration/VersionedKeyValueStoreIntegrationTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/kstream/internals/KStreamSlidingWindowAggregateTest.java": {
        "shard_count": 2
    },
    "src/test/java/org/apache/kafka/streams/processor/internals/HandlingSourceTopicDeletionIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/streams/processor/internals/StreamsAssignmentScaleTest.java": {
        "shard_count": 2,
        "tags": [
            "integration"
        ]
    },
    "streams-scala/src/test/scala/org/apache/kafka/streams/scala/StreamToTableJoinScalaIntegrationTestImplicitSerdes.scala": {
        "tags": [
            "integration"
        ]
    },
    "streams-scala/src/test/scala/org/apache/kafka/streams/scala/WordCountTest.scala": {
        "tags": [
            "integration"
        ]
    },
    "streams-scala/src/test/scala/org/apache/kafka/streams/scala/utils/StreamToTableJoinScalaIntegrationTestBase.scala": {
        "tags": [
            "integration"
        ]
    }
}
