# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/trogdor/coordinator/CoordinatorTest.java": {
        "tags": [
            "integration"
        ]
    }
}
