# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/clients/consumer/CooperativeStickyAssignorTest.java": {
        "shard_count": 2
    },
    "src/test/java/org/apache/kafka/common/memory/GarbageCollectedMemoryPoolTest.java": {
        "jvm_flags": [
            "-Xmx256m"
        ]
    },
    "src/test/java/org/apache/kafka/common/network/ReverseConnectionTest.java": {
        "shard_count": 2
    },
    "src/test/java/org/apache/kafka/common/network/SslTransportLayerTest.java": {
        "shard_count": 4,
        "size": "large"
    },
    "src/test/java/org/apache/kafka/common/network/Tls12SelectorTest.java": {
        "shard_count": 2
    },
    "src/test/java/org/apache/kafka/common/network/Tls13SelectorTest.java": {
        "shard_count": 2
    }
}
