# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/scala/org/apache/kafka/streams/scala/StreamToTableJoinScalaIntegrationTestImplicitSerdes.scala": {
        "tags": [
            "integration"
        ]
    },
    "src/test/scala/org/apache/kafka/streams/scala/WordCountTest.scala": {
        "tags": [
            "integration"
        ]
    },
    "src/test/scala/org/apache/kafka/streams/scala/utils/StreamToTableJoinScalaIntegrationTestBase.scala": {
        "tags": [
            "integration"
        ]
    }
}
