# This file is generated by bazel_tag_reader.py. Edits will be overwritten by
# bazel run //:gen_tags
per_test_args = {
    "src/test/java/org/apache/kafka/connect/file/integration/FileStreamSinkConnectorIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    },
    "src/test/java/org/apache/kafka/connect/file/integration/FileStreamSourceConnectorIntegrationTest.java": {
        "tags": [
            "integration"
        ]
    }
}
